apiVersion: v1
kind: Pod
metadata:
  name: spot-pod
  namespace: prod
spec:
  containers:
  - name: nginx
    image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: type
            operator: In
            values:
            - "spot"
  tolerations:
  - key: "instance_type"
    operator: "Equal"
    value: "spot"
    effect: "NoSchedule"
