name: Release Pipeline

on:
  push:
    branches:
    - develop
    - main
    - cicd

jobs:
  release:
    name: Release & Push to GAR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Release
      uses: huggingface/semver-release-action@latest
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Set LATEST_TAG environment variable
      id: set_latest_tag
      run: |
        echo "LATEST_TAG=$(git tag --list --sort=committerdate | tail -1)" >> $GITHUB_ENV
        echo "The latest tag is $LATEST_TAG"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: |
        cd ./src
        docker build -f ./docker/Dockerfile -t app:latest .

    - name: Tag Docker Image
      run: |
        docker tag app:latest ${{ vars.GAR_URL }}/${{ vars.IMAGE_NAME }}:$LATEST_TAG
        docker image ls
    
    # - name: Authenticate to GAR
    #   run: gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://${{ vars.REGION }}-docker.pkg.dev

    # - name: Push to GAR
    #   run: docker push ${{ vars.GAR_URL }}/${{ vars.IMAGE_NAME }}:$LATEST_TAG

