name: Release Pipeline

on:
  push:
    branches:
    - develop
    - main
    - cicd

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Release
      uses: huggingface/semver-release-action@latest
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - uses: 'google-github-actions/auth@v2'
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true


    # - name: Build Docker Image
    #   run: |
    #     docker build -t ${{ env.IMAGE_NAME }}:latest .
    #     docker image ls
