name: Release Pipeline

on:
  push:
    branches:
    - develop
    - main
    - cicd

jobs:
  release:
    name: Release & Push to GAR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Release
      uses: huggingface/semver-release-action@latest
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Extract region from gcloud CLI
      id: extract_region
      run: |
        echo "REGION=$(gcloud config get-value compute/region)" >> $GITHUB_ENV

    - name: Set LATEST_TAG environment variable
      id: set_latest_tag
      run: |
        echo "LATEST_TAG=$(git tag --list --sort=committerdate | tail -1)" >> $GITHUB_ENV

    - name: Echo' ing Project Variables
      run: |
        echo "The region is $REGION"
        echo "The latest tag is $LATEST_TAG"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: |
        cd ./src
        docker build -f ./docker/Dockerfile -t ${{ vars.IMAGE_NAME }}:latest .

    - name: Tag Docker Image
      run: |
        docker tag ${{ vars.IMAGE_NAME }}:latest ${{ vars.GAR_URL }}/${{ vars.IMAGE_NAME }}:$LATEST_TAG
        docker image ls

    - name: Authenticate to GAR
      run: gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://${REGION}-docker.pkg.dev

    - name: Push to GAR
      run: docker push ${{ vars.GAR_URL }}/${{ vars.IMAGE_NAME }}:$LATEST_TAG

