name: Release Pipeline

on:
  push:
    branches:
    - develop
    - main
    - cicd

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Release
      uses: huggingface/semver-release-action@latest
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    # - name: Authorize Docker for GCR
    #   run: gcloud auth configure-docker

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3


    - name: Build Docker Image
      run: |
        docker build -t ${{ env.IMAGE_NAME }}:latest .
        docker image ls
