name: Renovate Run

on:
  schedule:
    - cron: "30 16 * * 1-5"  # Every weekday at 10 PM
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Run Renovate
        uses: renovatebot/github-action@v32.63.1
        with:
          token: ${{ secrets.GH_TOKEN }}
